[package]
name = "todo_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
ratatui = { version = "0.27.0", features = ["all-widgets"] }
rusqlite = "0.31.0"
serde = { version = "1.0.203", features = ["serde_derive", "derive"] }
serde_json = "1.0.120"
